### ISSUE TITLE
Add support for Gnome 43

### ISSUE THREAD

**Issue by HydeFromT70s** [koolskateguy89/gnome-shell-extension-spotify-controller#20]
Hi,

Could you update your extension so it works on Gnome 43, please?

**Comment by sergiotca** [comment]
@koolskateguy89 buddy I just wanted to thank you for this extension, it was a life changer for me using Spotify daily while working. Since I updated to Gnome 43 I miss it to so bad I've even considered rolling back to 42 haha XD

Hopefully you find time to upgrade it anytime soon. 
Have a great holiday season!

**Comment by koolskateguy89** [comment]
Sorry I've been so inactive, I've been busy with uni work. Will do it now

**Comment by koolskateguy89** [comment]
Uploaded to EGO :+1:

**Comment by sergiotca** [comment]
> Uploaded to EGO +1

Wow that was fast! thank you buddy, best xmas gift ever! (◠‿◠)
